### ISSUE TITLE
strip the word "treact" from all themes

### ISSUE THREAD

**Issue by tedleyem** [tedleyem/react-themes#8]

**Comment by Sylar-codex** [comment]
So what am I to replace them with? Or should I just leave them blank?

**Comment by tedleyem** [comment]
Replace the word with "placeholder" for now

**Comment by Sylar-codex** [comment]
Already stripped treact, but didn’t strip them from package.json and manifest.json. Did this to avoid any code breakage and also a url. So far went ahead to monitor the code to see if it’ll affect anything but it wont. But wanted to run that through you before finally taking the step to replace the entire thing. Although I’ve pushed some so far.

**Comment by tedleyem** [comment]
Strip it from everywhere and rebuild locally to confirm it doesn't break anything

**Comment by Sylar-codex** [comment]
Already pushed this, it broke at first but wasn’t due to the name, so had to update all packages in the package.json. Works good now.

**Comment by Sylar-codex** [comment]
Created a PR

**Comment by tedleyem** [comment]
PR was approved and pushed
